# Generated by Django 2.0.1 on 2018-01-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCoinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycoin.MyCoin')),
            ],
        ),
    ]
