# Generated by Django 2.0.1 on 2018-01-05 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycoin', '0002_mycoinimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoin',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год чеканки'),
        ),
        migrations.AlterField(
            model_name='mycoin',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.Coin', verbose_name='Монета'),
        ),
        migrations.AlterField(
            model_name='mycoin',
            name='state',
            field=models.CharField(blank=True, choices=[('UNC', 'UNC'), ('AUNC', 'AUNC'), ('XF', 'XF'), ('VF', 'VF'), ('F', 'F'), ('G', 'G')], max_length=5, null=True, verbose_name='Состояние монеты'),
        ),
    ]
