# Generated by Django 2.0.1 on 2018-01-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoin', '0004_auto_20180105_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoinimage',
            name='type',
            field=models.CharField(choices=[('A', 'Avers'), ('B', 'Revers'), ('C', 'Gurt'), ('N', 'Other')], default='N', max_length=1),
        ),
    ]
