# Generated by Django 2.0.1 on 2018-01-05 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycoin', '0005_mycoinimage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoin',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
