# Generated by Django 2.0.1 on 2018-01-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycoin', '0006_mycoin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycoinimage',
            name='type',
            field=models.CharField(choices=[('A', 'Аверс'), ('B', 'Реверс'), ('C', 'Гурт'), ('N', 'Другое')], default='N', max_length=1),
        ),
    ]
