# Generated by Django 2.0.1 on 2018-01-04 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinlink',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.Coin'),
        ),
    ]
