# Generated by Django 2.0.1 on 2018-01-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180105_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='year',
        ),
        migrations.AddField(
            model_name='coin',
            name='circulation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тираж'),
        ),
        migrations.AddField(
            model_name='coin',
            name='year_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год начала чеканки'),
        ),
        migrations.AddField(
            model_name='coin',
            name='year_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год конца чеканки'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='title',
            field=models.TextField(verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='coin',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coin.CoinMaterial', verbose_name='Материал монеты'),
        ),
    ]
