# Generated by Django 2.0.1 on 2018-01-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_auto_20180105_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='kind',
            field=models.CharField(choices=[('A', 'Регулярный чекан'), ('B', 'Юбилейная')], default='A', max_length=1, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='coinimage',
            name='type',
            field=models.CharField(choices=[('A', 'Аверс'), ('B', 'Реверс'), ('C', 'Гурт'), ('N', 'Другое')], default='N', max_length=1),
        ),
    ]
