# Generated by Django 2.0.1 on 2018-01-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('coin', '0005_auto_20180105_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='tags',
            field=models.ManyToManyField(to='tags.CoinTags', verbose_name='Теги'),
        ),
    ]
