# Generated by Django 2.0.1 on 2018-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_coin_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
